### ISSUE TITLE
Additions to calculator functions

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#1910]
At our demonstration to SSD there was a request for the ifelse to be added to the set of logical functions.  before this is done I would like a discussion on other possible additional functions that could be useful.

Other possible additions are %in%, is.na, !is.na.  

I would also suggest we change the keyboard called **statistics** to **summary** .

We are loading dplyr and that includes the functions **first** and **last** and **nth**.  Would they be useful?  What about **any**, **all**.  What about **xor**?

Then do we want another keyboard called perhaps just "More".  We should think about a full list of further functions that would be useful.  Here are some that I would like:
1. **replace** - see for example http://stackoverflow.com/questions/11811027/replace-function-examples 
2. **duplicated** 
3. **cumulative functions**, namely cumsum, cumprod, cummax, cummin and then dplyr adds cummean, cumany, cumall, it says to "complete the set!
4. **diff** function
5. **lag** function.  There are a lot of these, so we should choose.  It is in base and dplyr.  Could use lag and lead from there.
6. A question - do we want to do row statistics in the calculator?  This could be "here" or may be a separate keyboard?
7. Moving average etc.  I wonder if the RcppRoll package can be used for this?  This is all it does, and it looks good and efficient.  It currently has 8 options.  There are special cases for alignment left, right or centre, but the default function, which gives centre has an optional argument, so that is the only one we need.  With 8 possibilities I wonder if rolling and cumulative is a keyboard on its own?
8. What else?  One area I would like it to be very strong in, would be in the text (character column) handling.  As we develop the special dialogues for this, within the Column: Text menu we should check what can also be here.  In general I see the calculator partly as a sort of stepping stone from some of the dialogues to using R itself.

Roger

**Comment by Lunalo** [comment]
@rdstern  

Can we also do a pipe operator(%>%) when using one dataframe for many operations?

**Comment by rdstern** [comment]
I wonder if that will work?  Would be exciting if it does.  I would not assume it for the beta at this late stage

**Comment by dannyparsons** [comment]
@Lunalo have any of these suggestions been implemented?

**Comment by volloholic** [comment]
@Lunalo update? are we pushing this back or is it done?

**Comment by Lunalo** [comment]
The additional group for the rowstats has already been implemented

**Comment by Lunalo** [comment]
@volloholic 

This can be closed since the issue has been addressed

**Comment by rdstern** [comment]
I have re-opened this issue.  John addressed some aspects and said it was done.  But I now wanted a diff function and there is also lag, etc.  We are still missing a keyboard.
Could this be a task for one of the new team?

**Comment by dannyparsons** [comment]
Yes if additional buttons/keyboards can be specified it's a good task for someone.

Ones I have used recently are `unique`, `length` and `ifelse`. I'm not sure if they are on any keyboard as I normally just type.

**Comment by rdstern** [comment]
OK.  Length is there, Stats, but called count!
unique I don't see because it produces a column of a different length.  How would you use it in the calculator.
ifelse would be nice!

As we do this it would be good also to tidy the keyboards a bit.  A good (I hope quite small) job for someone.
It would also be good to add tool-tips to some of the entries.

**Comment by dannyparsons** [comment]
Yes, that would be something of different length so I would just print it in the output window. Sometimes I do `length(unique(x))` and only do Try without saving, just to see how many unique values there are in a column get an idea of the variable. With `unique(x)` I would use Try or just display it in the output window. Not sure if this is how we want people to use the calculator though, just something I find useful. I can see how it could confuse once you get columns of different lengths.

**Comment by rdstern** [comment]
Interesting and I like all that.
I have now looked in more detail in what we might have in a new More keyboard.  Here is a partial list:
a) Your IFELSE function (Are there any more logical functions missing? 
b) Some weighted summaries might be interesting.  The base has weighted.mean.  Looking for other packages the one called matrixStats looks perhaps the most appropriate if we wanted weighted median, variance and standard deviation.  Perhaps we will soon be doing our own (more general) weights or using a survey package.  They are not so important.  We might just start with weighted.mean as it is so basic.
c) The big gap is lagging and differences and moving averages, etc.
1) I found the **lag** function seems to work - I assume it is a command from base or from stats.  It includes missing values as needed.
2) The ordinary diff function does not, because it doesn't pad with missing.  So the resulting column is a bit short.  I tested this and found that diff(c(NA,x)) is OK.
There are a lot of packages that could be used.  The one that seems obvious is zoo.  This has then both diff and also moving functions in a way that seem to cope with missing values.
4) Then there are the cumulative functions.  cumsum, cummax, cummin are in the base.  To get the cumulative mean you can use cumsum(x)/seq.along(x).  Note that if there are missing values then all after those are set to missing.
5) I think this might not be this keyboard, but become a missing keyboard.  We might want to be able to interpolate missing values.  We already have one function - to fill missing values from above or below.

**Comment by rdstern** [comment]
I am now using the **ifelse** function in the Guyana workshop.

We don't yet have the options in the Summarise to make the results missing if a proportion or number (>1) of values are missing.  The **ifelse** does this nicely.  It would be good if it were included.


I would put this new keyboard (in the calculator) in some form as quite a high priority for the November release.

**Comment by dannyparsons** [comment]
`ifelse` fits nicely into the logical keyboard? It would be good to look at the whole keyboard, doesn't have to be everyone, to think what we really want there and what are sensible groups.

**Comment by rdstern** [comment]
I agree.  We currently have a single Logical and Symbols keyboard.  Perhaps we separate them and just have Logical.  Extra symbols could go on the new More keyboard, or perhaps some could be there on an enlarged basic keyboard.  At the same time it would be good to look at details of the logical keys (at least.  For example there is one called **And**, which (thankfully) delivers **&**, while **OR** is there just as **|**.

**Comment by dannyparsons** [comment]
Are these all added now?

**Comment by rdstern** [comment]
So far I think the calculator is (temporarily ok).  So this can be closed.  That's not the same as the summary statistics.
There will be more soon, in a circular keyboard, but that should be a separate issue.
