### ISSUE TITLE
Recode Factors Bug - Crash

### ISSUE THREAD

**Issue by lilyclements** [africanmathsinitiative/R-Instat#2407]
This might already be a known bug, so apologies if this is the case.

If I use a factor column in Recode Factors
Then delete the column I used to create the new column
Then I reopen Recode Factors, there is a crash (see below)
I assume this is more an issue with the InstatDataObject than Recode Factors, since this problem could occur in other dialogs too?

---------------------------
Error running R command(s)
---------------------------
Error in stop(col_name, " is not a column in", get_metadata(data_name_label)) : 
  could not find function "get_metadata"

The error occurred in attempting to run the following R command(s):

convert_to_character_matrix(data=InstatDataObject$get_factor_data_frame(col_name="no", data_name="border_dataframe"))
---------------------------
OK   
---------------------------

**Comment by dannyparsons** [comment]
Yes good bug to fix. I guess it is caused by the factor data frame control. I can look into this.

**Comment by dannyparsons** [comment]
And this is a general bug with receivers. They should clear variables that no longer exist when they reopen.

**Comment by stevenndungu** [comment]
This can be closed. The bug was solved from my testing I guess.

**Comment by dannyparsons** [comment]
@lilyclements is this fixed now?

**Comment by lilyclements** [comment]
So, I've checked with the most recent branch and it still crashes. It takes you to line 113 of ucrFactor

            dfTemp = frmMain.clsRLink.RunInternalScriptGetValue(clsConvertToCharacter.ToScript()).AsDataFrame

**Comment by dannyparsons** [comment]
Ok thanks, I'll look into that.

**Comment by dannyparsons** [comment]
This is fixed and there was actually a general issue of the single receiver crashing when doing this on any dialog. Now fixed and this partially solves #1504 since variables that don't exist will be cleared in single receivers on reopen.

**Comment by rdstern** [comment]
Great!
