### ISSUE TITLE
Merge (and some other) dialogues don't work now

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7438]
**Describe the bug**
Program crashes when I use the merge dialogue  This could be caused by the controls changes by @Patowhiz ?  As @N-thony has queried, there may be pull requests to merge that will fix this?

**To Reproduce**
Steps to reproduce the behaviour:
Import from library the 3 data sets from the climdex package (not sure this is needed even, but it is what I did.)
Go to merge.
You don't get the dialogue.  Instead

![image](https://user-images.githubusercontent.com/11226469/166402834-03263ff5-774a-4f73-b2c6-ef4d7e0f3aea.png)

I am checking further and other dialogues also have a problem.  Summary and unstack were ok, but here is what happens with stack - after opening the survey data.
![image](https://user-images.githubusercontent.com/11226469/166403167-62a3ca5f-9338-4955-9d4d-6811079408c3.png)

**Comment by N-thony** [comment]
@rdstern this bug is fixed in PR #7415.

**Comment by rdstern** [comment]
@N-thony and @ChrisMarsh82 and @lloyddewit and I also see I approved last week!  So at last I have found something that I'm ahead of the others!

**Comment by lloyddewit** [comment]
> @rdstern this bug is fixed in PR #7415.

@N-thony I still have an open question in PR #7415. Please can you respond?
(or we can discuss verbally if that's easier)

**Comment by N-thony** [comment]
@lloyddewit as discussed, it is true that PR #7415 fix the issue in the Merge dialogue and it can be merge since it doesn't harm anything else. However, the problem is still there and it will be good to fix from the source. We suspect that the `controlvaluechanged` event is called a bit early as it isn't supposed too.
@Patowhiz hopefully you will look at it and fix it as reported in some others issues.

**Comment by N-thony** [comment]
Same problem with the `Duplicate Column`
![image](https://user-images.githubusercontent.com/68591383/166648301-220c2317-4dc2-496e-8946-5dc63a779abb.png)
