### ISSUE TITLE
Levels and Labels dialog translation doesn't match Crowdin

### ISSUE THREAD

**Issue by rachelkg** [africanmathsinitiative/R-Instat#7648]
Hello @lloyddewit, @N-thony and @dannyparsons 

Here is an other instance where the approved translation in Crowdin is not what is showing up in R-Instat. Add Factor Level should be Ajouter le niveau de facteur but instead it is still showing an old version Ajouter le facteur niveau. 

Is this a problem with how things have been approved? Please let me know if this is something i can fix, i would be happy to go through and check the approvals if so. 

Thanks, 

Rachel 
![2022-07-22_15-00-19](https://user-images.githubusercontent.com/85707390/180574610-029bda06-7101-4462-a636-363c8c37e9bb.png)
![2022-07-22_15-00-13](https://user-images.githubusercontent.com/85707390/180574615-1900bef7-52d7-4e50-9e47-35b564155dd9.png)

**Comment by lloyddewit** [comment]
@rachelkg I merged the latest CrowdIn changes into the database in PR #6569 and #7665. Does this solve the issue?
thanks

**Comment by rachelkg** [comment]
Yes! it seems to have resolved the issues where the tranlsation did not match the Crowdin entry. I will check and close the other issues it has resolved. 

It has not resolved the items that are showing up in English.

Thanks, 

Rachel

**Comment by lloyddewit** [comment]
> @lloyddewit Yes! it seems to have resolved the issues where the tranlsation did not match the Crowdin entry. I will check and close the other issues it has resolved.

@rachelkg happy it fixed some of the issues. The reason it didn't work earlier is that the CrowdIn changes hadn't been merged into the database. For the next few days (while we prepare the new release) I will merge the CrowdIn updates each day. You should then see the changes when you run the latest Master version of R-Instat.
 
> It has not resolved the items that are showing up in English.

There are 2 possible reasons for this:

1. The text is in CrowdIn but there is no French translation. In this case, you can add the translation to CrowdIn and I will merge it into the database.
2. The text is not yet in CrowdIn. In this case, @N-thony or I will need to take a few steps. Please let us know.
Thanks!

**Comment by rachelkg** [comment]
@lloyddewit 

As far as crowdin says the translation in there is 100%.

There are definitely items that are not in crowdin. The ones i have found are in issues: 

- #7599 
- #7647
- #7650 (this has lots that is not yet in crodwin but also also has a french item that is showing up in the English version)

There are also definitely items that used to be in French and are translated in Crowdin but not showing up in French now. The rightclick menus Issues: 

- #7601 
- #7645
- #7599 (the try button is translated correctly elsewhere but not here)

I hope that is clear. Please don't hesitate to let me know if you need more information. 

Thanks, 

Rachel 
My lists are not exhaustive but these are what I have come across so far.
