### ISSUE TITLE
Is the latest version of One Variable > Summarise > Customised installed?

### ISSUE THREAD

**Issue by rdstern** [africanmathsinitiative/R-Instat#7910]
@lilyclements this seems to work well in that it never crashes.  But I thought it could now produce some summaries for (ordered) factors or dates?
With the dodoma data the dates give the following results:
![image](https://user-images.githubusercontent.com/11226469/194918157-f61561cc-0290-4efd-9f23-ad95f2201c05.png)

I thought you had fixed it, so that minimum, maximum, etc were given, and even shown as dates?

With the ordered factors in the diamonds data I had wondered whether the minimum and maximum might be given - and the n-distinct would give the number of levels?

![image](https://user-images.githubusercontent.com/11226469/194918801-1575edb8-667e-4aa4-bb39-e1ffe8abc79c.png)

**Comment by lilyclements** [comment]
> I thought you had fixed it, so that minimum, maximum, etc were given, and even shown as dates?

@rdstern the mean/min/max/median changes are fixed here: #7465 - it is just yet to be merged

**Comment by rdstern** [comment]
I still don't see a difference in the One Variable summarise - for ordered factors:
![image](https://user-images.githubusercontent.com/11226469/202525092-9c71958f-5bef-4de6-81ab-8960907168f5.png)

or for dates:
![image](https://user-images.githubusercontent.com/11226469/202525350-61504cee-ee9e-43ca-875e-79310dc96d51.png)

So I wondered if perhaps the changes were added to the general dialogue.  So I tried this:

![image](https://user-images.githubusercontent.com/11226469/202525641-edeceb8a-1fda-42c6-8f0c-95077c926d00.png)
And it gave me this error:

![image](https://user-images.githubusercontent.com/11226469/202525846-09fd4765-0a58-422b-b2f9-b961311267ed.png)
The commands that gave the error were:
```
summary_table <- data_book$summary_table(data_name="dodoma", columns_to_summarise="date", treat_columns_as_factor=FALSE, j=1, summaries=c("summary_mean", "summary_min", "summary_max", "p25", "p75", "summary_median"))


last_table <- (mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary-variable'))
data_book$add_table(table_name="last_table", table=last_table, data_name="dodoma")
data_book$get_tables(data_name="dodoma", table_name="last_table")

rm(list=c("last_table", "summary_table"))

```
